# Generated by Django 3.0.7 on 2020-07-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0002_auto_20200711_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
