# Generated by Django 3.0.7 on 2020-07-11 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0004_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(verbose_name=2003),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, default='images/def.jpg', null=True, upload_to='images/')),
                ('school_name', models.CharField(max_length=30)),
                ('year_of_entry', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='Others', max_length=10)),
                ('major_courses', models.CharField(max_length=20)),
                ('minor_courses', models.CharField(max_length=20)),
                ('personal_interest', models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Body care', 'Body care'), ('Fashion', 'Fashion'), ('Gaming', 'Gaming'), ('Memes', 'Memes'), ('Gadget', 'Gadget'), ('Computer', 'Computer'), ('Music', 'Music'), ('Design', 'Design'), ('Business', 'Business'), ('Collaboration', 'Collaboration'), ('Health', 'Health'), ('Interior_design ', 'Interior_design '), ('Sport', 'Sport'), ('Food_and_drinks', 'Food_and_drinks'), ('Nature', 'Nature'), ('Photography', 'Photography'), ('Celebrities', 'Celebrities'), ('Movies', 'Movies'), ('Education', 'Education'), ('Innovation', 'Innovation'), ('Drawing', 'Drawing'), ('Animals', 'Animals')], max_length=50)),
                ('skills_you_have', models.CharField(max_length=40)),
                ('skills_you_dont_have', models.CharField(max_length=30)),
                ('hobbies', models.CharField(max_length=30)),
                ('heros_or_rolemodels', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extrasheet_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=40)),
                ('niche', models.CharField(max_length=18)),
                ('about_club', models.TextField(max_length=120)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extrasheet_club', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
