# Generated by Django 3.0.7 on 2020-07-12 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0005_auto_20200711_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club_in',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=20000)),
                ('upload_file', models.FileField(blank=True, upload_to='files/')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_update', to='extrasheet.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Club_fo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='club_comment', to='extrasheet.Club')),
            ],
        ),
    ]
