# Generated by Django 3.0.7 on 2020-07-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0007_club_re'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='club_image',
            field=models.ImageField(blank=True, default='images/def.jpg', null=True, upload_to='club_image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='personal_interest',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('programming', 'programming'), ('Entertainment', 'Entertainment'), ('Body care', 'Body care'), ('Fashion', 'Fashion'), ('Gaming', 'Gaming'), ('Memes', 'Memes'), ('Gadget', 'Gadget'), ('Computer', 'Computer'), ('Music', 'Music'), ('Design', 'Design'), ('Business', 'Business'), ('Collaboration', 'Collaboration'), ('Health', 'Health'), ('Interior_design ', 'Interior_design '), ('Sport', 'Sport'), ('Food_and_drinks', 'Food_and_drinks'), ('Nature', 'Nature'), ('Photography', 'Photography'), ('Celebrities', 'Celebrities'), ('Movies', 'Movies'), ('Education', 'Education'), ('Innovation', 'Innovation'), ('Drawing', 'Drawing'), ('Animals', 'Animals')], max_length=50),
        ),
    ]
