# Generated by Django 3.0.7 on 2020-07-12 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0009_auto_20200712_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='join',
            field=models.ManyToManyField(blank=True, related_name='join', to=settings.AUTH_USER_MODEL),
        ),
    ]
