# Generated by Django 3.0.7 on 2020-07-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0011_notify'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills_you_dont_have',
            new_name='skills_you_like_to_have',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_of_entry',
        ),
        migrations.AddField(
            model_name='profile',
            name='spoken_languages',
            field=models.CharField(default='English Language', max_length=50),
        ),
    ]
