# Generated by Django 3.0.7 on 2020-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0012_auto_20200719_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='about_club',
            field=models.TextField(max_length=58),
        ),
    ]
