# Generated by Django 3.0.7 on 2020-08-08 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('extrasheet', '0014_auto_20200725_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='club_fo',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='forum_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
